"use client";

import { useState } from "react";
import Navbar from "../components/Navbar";
import FeaturedMovie from "../components/FeaturedMovie";
import Hero from "../components/Hero";
import MovieCard from "../components/MovieCard";
import { movies } from "../data/movies";

export default function Home() {
	  const [search, setSearch] = useState("");

	    const searchTerm = search.trim().toLowerCase();

	      const filteredMovies = movies.filter((movie) => {
	      	    const titleMatch = movie.title
	      	          .toLowerCase()
	      	                .includes(searchTerm);

	      	                    const genreMatch = movie.genre
	      	                          .toLowerCase()
	      	                                .includes(searchTerm);

	      	                                    const yearMatch = movie.year
	      	                                          .toString()
	      	                                                .includes(searchTerm);

	      	                                                    const categoryMatch = movie.category
	      	                                                          .toLowerCase()
	      	                                                                .includes(searchTerm);

	      	                                                                    return (
	      	                                                                    	      titleMatch ||
	      	                                                                    	            genreMatch ||
	      	                                                                    	                  yearMatch ||
	      	                                                                    	                        categoryMatch
	      	                                                                    	                            );
	      	                                                                    	                              });

	      	                                                                    	                                const nollywoodMovies = movies.filter(
	      	                                                                    	                                	    (movie) => movie.category === "Nollywood"
	      	                                                                    	                                	      );

	      	                                                                    	                                	        const internationalMovies = movies.filter(
	      	                                                                    	                                	        	    (movie) => movie.category === "International"
	      	                                                                    	                                	        	      );

	      	                                                                    	                                	        	        const editorPicks = movies.filter(
	      	                                                                    	                                	        	        	    (movie) => movie.editorPick === true
	      	                                                                    	                                	        	        	      );

	      	                                                                    	                                	        	        	        const comingSoonMovies = movies.filter(
	      	                                                                    	                                	        	        	        	    (movie) => movie.comingSoon === true
	      	                                                                    	                                	        	        	        	      );

	      	                                                                    	                                	        	        	        	        return (
	      	                                                                    	                                	        	        	        	        	    <main className="min-h-screen bg-black text-white">
	      	                                                                    	                                	        	        	        	        	          <Navbar />

	      	                                                                    	                                	        	        	        	        	                <FeaturedMovie />

	      	                                                                    	                                	        	        	        	        	                      <Hero
	      	                                                                    	                                	        	        	        	        	                              search={search}
	      	                                                                    	                                	        	        	        	        	                                      setSearch={setSearch}
	      	                                                                    	                                	        	        	        	        	                                            />

	      	                                                                    	                                	        	        	        	        	                                                  {searchTerm ? (
	      	                                                                    	                                	        	        	        	        	                                                  	        <section className="px-6 pb-12">
	      	                                                                    	                                	        	        	        	        	                                                  	                  <h2 className="mb-6 text-2xl font-bold">
	      	                                                                    	                                	        	        	        	        	                                                  	                              🔍 Search Results
	      	                                                                    	                                	        	        	        	        	                                                  	                                        </h2>

	      	                                                                    	                                	        	        	        	        	                                                  	                                                  {filteredMovies.length > 0 ? (
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	            <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          {filteredMovies.map((movie) => (
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                <MovieCard
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                  key={movie.title}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                    movie={movie}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                    />
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                  ))}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                              </div>
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        ) : (
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	            <p className="text-gray-400">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                          No movies found for &quot;{search}&quot;.
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                      </p>
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                )}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                        </section>
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              ) : (
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	        <>
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                  <section className="px-6 pb-12">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                              <h2 className="mb-6 text-2xl font-bold">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                            📅 Coming Soon
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                        </h2>

	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                    <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  {comingSoonMovies.map((movie) => (
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                <MovieCard
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                  key={movie.title}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                    movie={movie}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                    />
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                  ))}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                              </div>
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                        </section>

	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                  <section className="px-6 pb-12">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                              <h2 className="mb-6 text-2xl font-bold">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                            🔥 Trending Movies
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                        </h2>

	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                    <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  {movies.map((movie) => (
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                <MovieCard
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                  key={movie.title}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                    movie={movie}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                    />
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                  ))}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                              </div>
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                        </section>

	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                  <section className="px-6 pb-12">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                              <h2 className="mb-6 text-2xl font-bold">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                            🇳🇬 Nollywood
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                        </h2>

	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                    <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  {nollywoodMovies.map((movie) => (
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                <MovieCard
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                  key={movie.title}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                    movie={movie}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                    />
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                  ))}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                              </div>
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                        </section>

	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                  <section className="px-6 pb-12">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                              <h2 className="mb-6 text-2xl font-bold">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                            🌍 International
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                        </h2>

	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                    <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  {internationalMovies.map((movie) => (
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                <MovieCard
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                  key={movie.title}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                    movie={movie}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                    />
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                  ))}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                              </div>
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                        </section>

	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                  <section className="px-6 pb-12">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                              <h2 className="mb-6 text-2xl font-bold">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                            ⭐ Editor&apos;s Picks
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                        </h2>

	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                    <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  {editorPicks.map((movie) => (
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                <MovieCard
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                  key={movie.title}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                    movie={movie}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                    />
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                  ))}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                              </div>
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                        </section>
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                </>
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                      )}
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                          </main>
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                            );
	      	                                                                    	                                	        	        	        	        	                                                  	                                                  	                          	                                                                                                        	                                                              	                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                                                                                  	                                                                                                                            }
