import Image from "next/image";
import { movies } from "../../../data/movies";
import BackButton from "../../../components/BackButton";

type Props = {
	  params: Promise<{
	  	    title: string;
	  	      }>;
	  	      };

	  	      export default async function MovieDetails({ params }: Props) {
	  	      	  const { title } = await params;

	  	      	    const movie = movies.find(
	  	      	    	    (item) =>
	  	      	    	          item.title.toLowerCase() ===
	  	      	    	                decodeURIComponent(title).toLowerCase()
	  	      	    	                  );

	  	      	    	                    if (!movie) {
	  	      	    	                    	    return (
	  	      	    	                    	    	      <main className="flex min-h-screen items-center justify-center bg-black px-6 text-white">
	  	      	    	                    	    	              <div className="text-center">
	  	      	    	                    	    	                        <div className="mb-4 text-6xl">🎬</div>

	  	      	    	                    	    	                                  <h1 className="text-3xl font-bold">
	  	      	    	                    	    	                                              Movie Not Found
	  	      	    	                    	    	                                                        </h1>

	  	      	    	                    	    	                                                                  <p className="mt-2 text-gray-400">
	  	      	    	                    	    	                                                                              We couldn&apos;t find this movie on FILMYIMIKA.
	  	      	    	                    	    	                                                                                        </p>

	  	      	    	                    	    	                                                                                                  <div className="mt-6">
	  	      	    	                    	    	                                                                                                              <BackButton />
	  	      	    	                    	    	                                                                                                                        </div>
	  	      	    	                    	    	                                                                                                                                </div>
	  	      	    	                    	    	                                                                                                                                      </main>
	  	      	    	                    	    	                                                                                                                                          );
	  	      	    	                    	    	                                                                                                                                            }

	  	      	    	                    	    	                                                                                                                                              return (
	  	      	    	                    	    	                                                                                                                                              	    <main className="min-h-screen bg-black text-white">
	  	      	    	                    	    	                                                                                                                                              	          <div className="mx-auto max-w-6xl px-6 py-8 md:py-12">

	  	      	    	                    	    	                                                                                                                                              	                  <BackButton />

	  	      	    	                    	    	                                                                                                                                              	                          <div className="mt-8 grid items-start gap-10 md:grid-cols-2">

	  	      	    	                    	    	                                                                                                                                              	                                    <div className="relative">
	  	      	    	                    	    	                                                                                                                                              	                                                <Image
	  	      	    	                    	    	                                                                                                                                              	                                                              src={movie.image}
	  	      	    	                    	    	                                                                                                                                              	                                                                            alt={movie.title}
	  	      	    	                    	    	                                                                                                                                              	                                                                                          width={600}
	  	      	    	                    	    	                                                                                                                                              	                                                                                                        height={900}
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                      priority
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                    className="mx-auto w-full max-w-md rounded-2xl object-cover shadow-2xl"
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                />

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            {movie.comingSoon && (
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	              <div className="absolute left-4 top-4 rounded-lg bg-red-600 px-3 py-2 text-sm font-bold">
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                              📅 Coming Soon
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                            </div>
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                        )}
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                  </div>

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                            <div className="pt-2 md:pt-6">

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                        <p className="text-sm font-semibold uppercase tracking-widest text-yellow-400">
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                      {movie.category}
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                  </p>

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                              <h1 className="mt-3 text-4xl font-extrabold leading-tight md:text-5xl">
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                            {movie.title}
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                        </h1>

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                    <div className="mt-5 flex flex-wrap gap-3">
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                  <span className="rounded-full bg-gray-800 px-4 py-2 text-sm text-gray-300">
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                  📅 {movie.year}
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                </span>

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                              <span className="rounded-full bg-gray-800 px-4 py-2 text-sm text-gray-300">
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                              🎭 {movie.genre}
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                            </span>

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                          <span className="rounded-full bg-yellow-500 px-4 py-2 text-sm font-bold text-black">
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                          ⭐ {movie.rating}
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                        </span>
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                    </div>

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                <div className="mt-8">
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                              <h2 className="text-xl font-bold">
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                              About the Movie
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                            </h2>

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                          <p className="mt-3 leading-7 text-gray-300">
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                          {movie.description}
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-8 flex flex-wrap gap-4">

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                              href={movie.trailer}
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              target="_blank"
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rel="noopener noreferrer"
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="rounded-xl bg-yellow-500 px-6 py-3 font-bold text-black transition hover:bg-yellow-400"
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ▶ Watch Trailer
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </a>

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="rounded-xl border border-gray-700 px-6 py-3 font-bold text-white transition hover:bg-gray-900"
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      + Add to Watchlist
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <section className="mt-16 border-t border-gray-800 pt-10">
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 className="text-2xl font-bold">
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                More Like This
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h2>

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="mt-2 text-gray-400">
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Discover more movies coming to FILMYIMIKA.
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>

	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
	  	      	    	                    	    	                                                                                                                                              	                                                                                                                                                            	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
